added additional options for compiler support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -857,6 +857,9 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-ibm            compile P3DFFT using IBM compiler
+  --enable-pgi            compile P3DFFT using PGI compiler
+  --enable-gcc            compile P3DFFT using GCC compiler
   --enable-single         compile P3DFFT in single precision (default is
                           double precision)
   --enable-oned           for 1D decomposition (default is 2D but it can be
@@ -870,8 +873,6 @@ Optional Features:
                           much more time on p3dfft_setup()).
   --enable-dimsc          to assign processor rows and columns according to C
                           convention, rather than "Fortran", which is default.
-  --enable-reversedims    to interchange processor rows and columns from
-                          default.
   --enable-useeven        for using MPI_Alltoall instead of MPI_Alltotallv.
                           This method pads the send buffers with zeros to make
                           them equal size. This options is not needed on most
@@ -883,6 +884,7 @@ Optional Features:
                           set to default values.
   --enable-nblx           to define loop blocking factor NBL_X
   --enable-nbly           to define loop blocking factor NBL_Y
+  --enable-fftw           for using the FFTW library (default)
   --enable-essl           for using ESSL (on IBM) in 1D FFTs.
 
 Optional Packages:
@@ -1791,6 +1793,73 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
           ac_config_headers="$ac_config_headers config.h"
 
 
+
+# check whether to compile using IBM
+echo "$as_me:$LINENO: checking whether to use IBM compiler" >&5
+echo $ECHO_N "checking whether to use IBM compiler... $ECHO_C" >&6
+# Check whether --enable-ibm or --disable-ibm was given.
+if test "${enable_ibm+set}" = set; then
+  enableval="$enable_ibm"
+  ok=$enableval
+else
+  ok=no
+fi;
+echo "$as_me:$LINENO: result: $ok" >&5
+echo "${ECHO_T}$ok" >&6
+if test "$ok" = "yes"; then
+        DFLAGS="$DFLAGS -DIBM"
+
+
+cat >>confdefs.h <<\_ACEOF
+#define IBM 1
+_ACEOF
+
+fi
+
+# check whether to compile using PGI
+echo "$as_me:$LINENO: checking whether to use PGI compiler" >&5
+echo $ECHO_N "checking whether to use PGI compiler... $ECHO_C" >&6
+# Check whether --enable-pgi or --disable-pgi was given.
+if test "${enable_pgi+set}" = set; then
+  enableval="$enable_pgi"
+  ok=$enableval
+else
+  ok=no
+fi;
+echo "$as_me:$LINENO: result: $ok" >&5
+echo "${ECHO_T}$ok" >&6
+if test "$ok" = "yes"; then
+        DFLAGS="$DFLAGS -DPGI"
+
+
+cat >>confdefs.h <<\_ACEOF
+#define PGI 1
+_ACEOF
+
+fi
+
+# check whether to compile using GCC
+echo "$as_me:$LINENO: checking whether to use GCC compiler" >&5
+echo $ECHO_N "checking whether to use GCC compiler... $ECHO_C" >&6
+# Check whether --enable-gcc or --disable-gcc was given.
+if test "${enable_gcc+set}" = set; then
+  enableval="$enable_gcc"
+  ok=$enableval
+else
+  ok=no
+fi;
+echo "$as_me:$LINENO: result: $ok" >&5
+echo "${ECHO_T}$ok" >&6
+if test "$ok" = "yes"; then
+        DFLAGS="$DFLAGS -DGCC"
+
+
+cat >>confdefs.h <<\_ACEOF
+#define GCC 1
+_ACEOF
+
+fi
+
 # check whether to enable single precision
 echo "$as_me:$LINENO: checking whether to enable single precision" >&5
 echo $ECHO_N "checking whether to enable single precision... $ECHO_C" >&6
@@ -1843,7 +1912,7 @@ if test "${enable_estimate+set}" = set; then
   enableval="$enable_estimate"
   ok=$enableval
 else
-  ok=no
+  ok=yes
 fi;
 echo "$as_me:$LINENO: result: $ok" >&5
 echo "${ECHO_T}$ok" >&6
@@ -1858,8 +1927,8 @@ _ACEOF
 fi
 
 # check whether to enable the measure algorithm
-echo "$as_me:$LINENO: checking whether to enable the emasure algorithm" >&5
-echo $ECHO_N "checking whether to enable the emasure algorithm... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking whether to enable the measure algorithm" >&5
+echo $ECHO_N "checking whether to enable the measure algorithm... $ECHO_C" >&6
 # Check whether --enable-measure or --disable-measure was given.
 if test "${enable_measure+set}" = set; then
   enableval="$enable_measure"
@@ -1924,26 +1993,13 @@ _ACEOF
 fi
 
 # check whether to reverse processor dimensions
-echo "$as_me:$LINENO: checking whether to reverse processor dimensions" >&5
-echo $ECHO_N "checking whether to reverse processor dimensions... $ECHO_C" >&6
-# Check whether --enable-reversedims or --disable-reversedims was given.
-if test "${enable_reversedims+set}" = set; then
-  enableval="$enable_reversedims"
-  ok=$enableval
-else
-  ok=yes
-fi;
-echo "$as_me:$LINENO: result: $ok" >&5
-echo "${ECHO_T}$ok" >&6
-if test "$ok" = "yes"; then
-	DFLAGS="$DFLAGS -DREVERSE_DIMS"
-
-
-cat >>confdefs.h <<\_ACEOF
-#define REVERSE 1
-_ACEOF
-
-fi
+# AC_MSG_CHECKING([whether to reverse processor dimensions])
+# AC_ARG_ENABLE(reversedims, [AC_HELP_STRING([--enable-reversedims], [to interchange processor rows and columns from default.])], ok=$enableval, ok=yes)
+# AC_MSG_RESULT([$ok])
+# if test "$ok" = "yes"; then
+#	AC_SUBST(DFLAGS, "$DFLAGS -DREVERSE_DIMS")
+#	AC_DEFINE(REVERSE, 1, [Define if you want to reverse processor dimensions])
+# fi
 
 # check whether to use MPI_Alltoall instead of MPI_Alltotallv
 echo "$as_me:$LINENO: checking whether to use MPI_Alltoall instead of MPI_Alltotallv" >&5
@@ -2039,6 +2095,28 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+# check whether to use FFTW
+echo "$as_me:$LINENO: checking whether to use FFTW library" >&5
+echo $ECHO_N "checking whether to use FFTW library... $ECHO_C" >&6
+# Check whether --enable-essl or --disable-essl was given.
+if test "${enable_essl+set}" = set; then
+  enableval="$enable_essl"
+  fftwval=$enableval
+else
+  fftwval=yes
+fi;
+echo "$as_me:$LINENO: result: $fftwval" >&5
+echo "${ECHO_T}$fftwval" >&6
+if test "$fftwval" = "yes"; then
+        DFLAGS="DFLAGS -DFFTW"
+
+
+cat >>confdefs.h <<\_ACEOF
+#define FFTW 1
+_ACEOF
+
+fi
+
 # check whether to use ESSL
 echo "$as_me:$LINENO: checking whether to use ESSL library" >&5
 echo $ECHO_N "checking whether to use ESSL library... $ECHO_C" >&6
@@ -2061,9 +2139,21 @@ _ACEOF
 
 fi
 
+# check to see if FFTW or ESSL has been selected
+if test "$fftwval" == "no" && test "$esslval" == "no"; then
+        { { echo "$as_me:$LINENO: error: You must choose to use either ESSL or FFTW!" >&5
+echo "$as_me: error: You must choose to use either ESSL or FFTW!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+# check to see if FFTW and ESSL have both been selected
+if test "$fftwval" == "yes" && test "$esslval" == "yes"; then
+        { { echo "$as_me:$LINENO: error: You must only choose either ESSL or FFTW!" >&5
+echo "$as_me: error: You must only choose either ESSL or FFTW!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 # check for fftw3
-echo "$as_me:$LINENO: checking whether to use FFTW library" >&5
-echo $ECHO_N "checking whether to use FFTW library... $ECHO_C" >&6
 
 # Check whether --with-fftw or --without-fftw was given.
 if test "${with_fftw+set}" = set; then
@@ -2073,41 +2163,20 @@ else
   withfftw=""
 fi;
 if test "$withfftw" != ""; then
-	echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-	DFLAGS="$DFLAGS -DFFTW"
-
 	FFTW_INC="$withfftw/include"
 
 	FFTW_LIB="$withfftw/lib"
-
-
-cat >>confdefs.h <<\_ACEOF
-#define FFTW 1
-_ACEOF
-
 
 	if test "$spval" == "yes"; then
 		FFTWF="$FFTW_LIB/libfftw3f.a"
 
 	fi
 else
-	echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-# check to see if FFTW or ESSL has been selected
-if test "$withfftw" == "" && test "$esslval" == "no"; then
-	{ { echo "$as_me:$LINENO: error: You must choose to use either ESSL or FFTW!" >&5
-echo "$as_me: error: You must choose to use either ESSL or FFTW!" >&2;}
+	if test "$fftwval" == "yes"; then
+		{ { echo "$as_me:$LINENO: error: location to FFTW was not given!" >&5
+echo "$as_me: error: location to FFTW was not given!" >&2;}
    { (exit 1); exit 1; }; }
-fi
-
-# check to see if FFTW and ESSL have both been selected
-if test "$withfftw" != "" && test "$esslval" == "yes"; then
-	{ { echo "$as_me:$LINENO: error: You must only choose either ESSL or FFTW!" >&5
-echo "$as_me: error: You must only choose either ESSL or FFTW!" >&2;}
-   { (exit 1); exit 1; }; }
+	fi
 fi
 
 # Checks for programs.
@@ -2203,7 +2272,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2206:" \
+echo "$as_me:2275:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
